[workspace]
members = ["backend/server", "backend/domain", "backend/errors", "backend/macros", "backend/migration", "backend/email_verification_code", "client/src-tauri", "backend/hasher"]
resolver = "3"
