version: "3.8"
services:
  database:
    image: postgres:17
    container_name: hearth-postgres
    environment:
      POSTGRES_DB: hearth
      POSTGRES_PASSWORD: hearth
      POSTGRES_USER: hearth
    ports:
      - 5432:5432
    restart: on-failure:3

  redis:
    image: redis:latest
    container_name: hearth-redis
    command: redis-server
    ports:
      - 6379:6379
