[package]
name = "email_verification_code"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
regex = "1.12.2"
validator = { version = "0.20.0", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }