[package]
name = "errors"
version = "0.1.0"
edition = "2024"

[dependencies]
validator = "0.20.0"
serde = { version = "1.0.228", features = ["derive"] }
actix-web = { version = "4", default-features = false }
serde_json = "1.0.145"
thiserror = "2.0.17"
